import { Inter } from "next/font/google";
import "./globals.css";
import TransitionPresence from "@/components/transitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rajesh Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionPresence>{children}</TransitionPresence>
      </body>
    </html>
  );
}
